### ISSUE TITLE
sql文件

### ISSUE THREAD

**Issue by wmhy** [maliangnansheng/bbs-ssm#1]
你好，你的sql文件存放在项目的哪个位置呢？我找了下没有找到

**Comment by wmhy** [comment]
呃，不好意思，老眼昏花了。。。

**Comment by ziyoubeighb** [comment]
> 呃，不好意思，老眼昏花了。。。

你找到了？

**Comment by cutety** [comment]
???找不到啊

**Comment by hoodlum3825** [comment]
我都找不到SQL文件

**Comment by maliangnansheng** [comment]
加我qq(924818949)吧，拉你进群，里面有------------------ 原始邮件 ------------------
发件人: "hoodlum3825"<notifications@github.com>
发送时间: 2019年12月12日(星期四) 下午3:21
收件人: "maliangnansheng/bbs-ssm"<bbs-ssm@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [maliangnansheng/bbs-ssm] sql文件 (#1)



我都找不到SQL文&#x4EF6;
 
&mdash;

**Comment by hoodlum3825** [comment]
> 加我qq(924818949)吧，拉你进群，里面有------------------ 原始邮件 ------------------ 发件人: "hoodlum3825"<notifications@github.com> 发送时间: 2019年12月12日(星期四) 下午3:21 收件人: "maliangnansheng/bbs-ssm"<bbs-ssm@noreply.github.com>; 抄送: "Subscribed"<subscribed@noreply.github.com>; 主题: Re: [maliangnansheng/bbs-ssm] sql文件 (#1) 我都找不到SQL文&#x4EF6; &mdash; You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

已加你QQ

**Comment by kenghuang** [comment]
找不到SQL文件

**Comment by maliangnansheng** [comment]
加qq：924818949发你们数据库文件

**Comment by tt9436929** [comment]
能发一下sql文件吗？993512919

**Comment by JohanOu** [comment]
我加了，麻烦通过一下好友，谢谢大佬

**Comment by onkenut** [comment]
where is the "sql"?

**Comment by maliangnansheng** [comment]
加qq：924818949发你们数据库文件
